
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="zh_Hans">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Django Exceptions &#8212; Django 2.1.8.dev20190330215650 文档</title>
    <link rel="stylesheet" href="../_static/default.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <script type="text/javascript" id="documentation_options" data-url_root="../" src="../_static/documentation_options.js"></script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <script type="text/javascript" src="../_static/language_data.js"></script>
    <link rel="index" title="索引" href="../genindex.html" />
    <link rel="search" title="搜索" href="../search.html" />
    <link rel="next" title="File handling" href="files/index.html" />
    <link rel="prev" title="django-admin and manage.py" href="django-admin.html" />



 
<script type="text/javascript" src="../templatebuiltins.js"></script>
<script type="text/javascript">
(function($) {
    if (!django_template_builtins) {
       // templatebuiltins.js missing, do nothing.
       return;
    }
    $(document).ready(function() {
        // Hyperlink Django template tags and filters
        var base = "templates/builtins.html";
        if (base == "#") {
            // Special case for builtins.html itself
            base = "";
        }
        // Tags are keywords, class '.k'
        $("div.highlight\\-html\\+django span.k").each(function(i, elem) {
             var tagname = $(elem).text();
             if ($.inArray(tagname, django_template_builtins.ttags) != -1) {
                 var fragment = tagname.replace(/_/, '-');
                 $(elem).html("<a href='" + base + "#" + fragment + "'>" + tagname + "</a>");
             }
        });
        // Filters are functions, class '.nf'
        $("div.highlight\\-html\\+django span.nf").each(function(i, elem) {
             var filtername = $(elem).text();
             if ($.inArray(filtername, django_template_builtins.tfilters) != -1) {
                 var fragment = filtername.replace(/_/, '-');
                 $(elem).html("<a href='" + base + "#" + fragment + "'>" + filtername + "</a>");
             }
        });
    });
})(jQuery);</script>

  </head><body>

    <div class="document">
  <div id="custom-doc" class="yui-t6">
    <div id="hd">
      <h1><a href="../index.html">Django 2.1.8.dev20190330215650 文档</a></h1>
      <div id="global-nav">
        <a title="Home page" href="../index.html">Home</a>  |
        <a title="Table of contents" href="../contents.html">Table of contents</a>  |
        <a title="Global index" href="../genindex.html">Index</a>  |
        <a title="Module index" href="../py-modindex.html">Modules</a>
      </div>
      <div class="nav">
    &laquo; <a href="django-admin.html" title="&lt;code class=&#34;docutils literal notranslate&#34;&gt;&lt;span class=&#34;pre&#34;&gt;django-admin&lt;/span&gt;&lt;/code&gt; and &lt;code class=&#34;docutils literal notranslate&#34;&gt;&lt;span class=&#34;pre&#34;&gt;manage.py&lt;/span&gt;&lt;/code&gt;">previous</a>
     |
    <a href="index.html" title="API Reference" accesskey="U">up</a>
   |
    <a href="files/index.html" title="File handling">next</a> &raquo;</div>
    </div>

    <div id="bd">
      <div id="yui-main">
        <div class="yui-b">
          <div class="yui-g" id="ref-exceptions">
            
  <div class="section" id="s-django-exceptions">
<span id="django-exceptions"></span><h1>Django Exceptions<a class="headerlink" href="#django-exceptions" title="永久链接至标题">¶</a></h1>
<p>Django raises some of its own exceptions as well as standard Python exceptions.</p>
<div class="section" id="s-module-django.core.exceptions">
<span id="s-django-core-exceptions"></span><span id="module-django.core.exceptions"></span><span id="django-core-exceptions"></span><h2>Django Core Exceptions<a class="headerlink" href="#module-django.core.exceptions" title="永久链接至标题">¶</a></h2>
<p>Django core exception classes are defined in <code class="docutils literal notranslate"><span class="pre">django.core.exceptions</span></code>.</p>
<div class="section" id="s-appregistrynotready">
<span id="appregistrynotready"></span><h3><code class="docutils literal notranslate"><span class="pre">AppRegistryNotReady</span></code><a class="headerlink" href="#appregistrynotready" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.AppRegistryNotReady">
<em class="property">exception </em><code class="descname">AppRegistryNotReady</code><a class="reference internal" href="../_modules/django/core/exceptions.html#AppRegistryNotReady"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.AppRegistryNotReady" title="永久链接至目标">¶</a></dt>
<dd><p>This exception is raised when attempting to use models before the <a class="reference internal" href="applications.html#app-loading-process"><span class="std std-ref">app
loading process</span></a>, which initializes the ORM, is
complete.</p>
</dd></dl>

</div>
<div class="section" id="s-objectdoesnotexist">
<span id="objectdoesnotexist"></span><h3><code class="docutils literal notranslate"><span class="pre">ObjectDoesNotExist</span></code><a class="headerlink" href="#objectdoesnotexist" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ObjectDoesNotExist">
<em class="property">exception </em><code class="descname">ObjectDoesNotExist</code><a class="reference internal" href="../_modules/django/core/exceptions.html#ObjectDoesNotExist"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.ObjectDoesNotExist" title="永久链接至目标">¶</a></dt>
<dd><p>The base class for <a class="reference internal" href="models/instances.html#django.db.models.Model.DoesNotExist" title="django.db.models.Model.DoesNotExist"><code class="xref py py-exc docutils literal notranslate"><span class="pre">DoesNotExist</span></code></a> exceptions;
a <code class="docutils literal notranslate"><span class="pre">try/except</span></code> for <code class="docutils literal notranslate"><span class="pre">ObjectDoesNotExist</span></code> will catch
<a class="reference internal" href="models/instances.html#django.db.models.Model.DoesNotExist" title="django.db.models.Model.DoesNotExist"><code class="xref py py-exc docutils literal notranslate"><span class="pre">DoesNotExist</span></code></a> exceptions for all models.</p>
<p>See <a class="reference internal" href="models/querysets.html#django.db.models.query.QuerySet.get" title="django.db.models.query.QuerySet.get"><code class="xref py py-meth docutils literal notranslate"><span class="pre">get()</span></code></a> for further information
on <a class="reference internal" href="#django.core.exceptions.ObjectDoesNotExist" title="django.core.exceptions.ObjectDoesNotExist"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ObjectDoesNotExist</span></code></a> and <a class="reference internal" href="models/instances.html#django.db.models.Model.DoesNotExist" title="django.db.models.Model.DoesNotExist"><code class="xref py py-exc docutils literal notranslate"><span class="pre">DoesNotExist</span></code></a>.</p>
</dd></dl>

</div>
<div class="section" id="s-emptyresultset">
<span id="emptyresultset"></span><h3><code class="docutils literal notranslate"><span class="pre">EmptyResultSet</span></code><a class="headerlink" href="#emptyresultset" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.EmptyResultSet">
<em class="property">exception </em><code class="descname">EmptyResultSet</code><a class="reference internal" href="../_modules/django/core/exceptions.html#EmptyResultSet"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.EmptyResultSet" title="永久链接至目标">¶</a></dt>
<dd><p><code class="docutils literal notranslate"><span class="pre">EmptyResultSet</span></code> may be raised during query generation if a query won't
return any results. Most Django projects won't encounter this exception,
but it might be useful for implementing custom lookups and expressions.</p>
</dd></dl>

</div>
<div class="section" id="s-fielddoesnotexist">
<span id="fielddoesnotexist"></span><h3><code class="docutils literal notranslate"><span class="pre">FieldDoesNotExist</span></code><a class="headerlink" href="#fielddoesnotexist" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.FieldDoesNotExist">
<em class="property">exception </em><code class="descname">FieldDoesNotExist</code><a class="reference internal" href="../_modules/django/core/exceptions.html#FieldDoesNotExist"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.FieldDoesNotExist" title="永久链接至目标">¶</a></dt>
<dd><p>The <code class="docutils literal notranslate"><span class="pre">FieldDoesNotExist</span></code> exception is raised by a model's
<code class="docutils literal notranslate"><span class="pre">_meta.get_field()</span></code> method when the requested field does not exist on the
model or on the model's parents.</p>
</dd></dl>

</div>
<div class="section" id="s-multipleobjectsreturned">
<span id="multipleobjectsreturned"></span><h3><code class="docutils literal notranslate"><span class="pre">MultipleObjectsReturned</span></code><a class="headerlink" href="#multipleobjectsreturned" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.MultipleObjectsReturned">
<em class="property">exception </em><code class="descname">MultipleObjectsReturned</code><a class="reference internal" href="../_modules/django/core/exceptions.html#MultipleObjectsReturned"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.MultipleObjectsReturned" title="永久链接至目标">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.MultipleObjectsReturned" title="django.core.exceptions.MultipleObjectsReturned"><code class="xref py py-exc docutils literal notranslate"><span class="pre">MultipleObjectsReturned</span></code></a> exception is raised by a query if only
one object is expected, but multiple objects are returned. A base version
of this exception is provided in <a class="reference internal" href="#module-django.core.exceptions" title="django.core.exceptions: Django core exceptions"><code class="xref py py-mod docutils literal notranslate"><span class="pre">django.core.exceptions</span></code></a>; each model
class contains a subclassed version that can be used to identify the
specific object type that has returned multiple objects.</p>
<p>See <a class="reference internal" href="models/querysets.html#django.db.models.query.QuerySet.get" title="django.db.models.query.QuerySet.get"><code class="xref py py-meth docutils literal notranslate"><span class="pre">get()</span></code></a> for further information.</p>
</dd></dl>

</div>
<div class="section" id="s-suspiciousoperation">
<span id="suspiciousoperation"></span><h3><code class="docutils literal notranslate"><span class="pre">SuspiciousOperation</span></code><a class="headerlink" href="#suspiciousoperation" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.SuspiciousOperation">
<em class="property">exception </em><code class="descname">SuspiciousOperation</code><a class="reference internal" href="../_modules/django/core/exceptions.html#SuspiciousOperation"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.SuspiciousOperation" title="永久链接至目标">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.SuspiciousOperation" title="django.core.exceptions.SuspiciousOperation"><code class="xref py py-exc docutils literal notranslate"><span class="pre">SuspiciousOperation</span></code></a> exception is raised when a user has
performed an operation that should be considered suspicious from a security
perspective, such as tampering with a session cookie. Subclasses of
<code class="docutils literal notranslate"><span class="pre">SuspiciousOperation</span></code> include:</p>
<ul class="simple">
<li><code class="docutils literal notranslate"><span class="pre">DisallowedHost</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">DisallowedModelAdminLookup</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">DisallowedModelAdminToField</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">DisallowedRedirect</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">InvalidSessionKey</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">RequestDataTooBig</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">SuspiciousFileOperation</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">SuspiciousMultipartForm</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">SuspiciousSession</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">TooManyFieldsSent</span></code></li>
</ul>
<p>If a <code class="docutils literal notranslate"><span class="pre">SuspiciousOperation</span></code> exception reaches the WSGI handler level it is
logged at the <code class="docutils literal notranslate"><span class="pre">Error</span></code> level and results in
a <a class="reference internal" href="request-response.html#django.http.HttpResponseBadRequest" title="django.http.HttpResponseBadRequest"><code class="xref py py-class docutils literal notranslate"><span class="pre">HttpResponseBadRequest</span></code></a>. See the <a class="reference internal" href="../topics/logging.html"><span class="doc">logging
documentation</span></a> for more information.</p>
</dd></dl>

</div>
<div class="section" id="s-permissiondenied">
<span id="permissiondenied"></span><h3><code class="docutils literal notranslate"><span class="pre">PermissionDenied</span></code><a class="headerlink" href="#permissiondenied" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.PermissionDenied">
<em class="property">exception </em><code class="descname">PermissionDenied</code><a class="reference internal" href="../_modules/django/core/exceptions.html#PermissionDenied"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.PermissionDenied" title="永久链接至目标">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.PermissionDenied" title="django.core.exceptions.PermissionDenied"><code class="xref py py-exc docutils literal notranslate"><span class="pre">PermissionDenied</span></code></a> exception is raised when a user does not have
permission to perform the action requested.</p>
</dd></dl>

</div>
<div class="section" id="s-viewdoesnotexist">
<span id="viewdoesnotexist"></span><h3><code class="docutils literal notranslate"><span class="pre">ViewDoesNotExist</span></code><a class="headerlink" href="#viewdoesnotexist" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ViewDoesNotExist">
<em class="property">exception </em><code class="descname">ViewDoesNotExist</code><a class="reference internal" href="../_modules/django/core/exceptions.html#ViewDoesNotExist"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.ViewDoesNotExist" title="永久链接至目标">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.ViewDoesNotExist" title="django.core.exceptions.ViewDoesNotExist"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ViewDoesNotExist</span></code></a> exception is raised by
<a class="reference internal" href="urlresolvers.html#module-django.urls" title="django.urls"><code class="xref py py-mod docutils literal notranslate"><span class="pre">django.urls</span></code></a> when a requested view does not exist.</p>
</dd></dl>

</div>
<div class="section" id="s-middlewarenotused">
<span id="middlewarenotused"></span><h3><code class="docutils literal notranslate"><span class="pre">MiddlewareNotUsed</span></code><a class="headerlink" href="#middlewarenotused" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.MiddlewareNotUsed">
<em class="property">exception </em><code class="descname">MiddlewareNotUsed</code><a class="reference internal" href="../_modules/django/core/exceptions.html#MiddlewareNotUsed"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.MiddlewareNotUsed" title="永久链接至目标">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.MiddlewareNotUsed" title="django.core.exceptions.MiddlewareNotUsed"><code class="xref py py-exc docutils literal notranslate"><span class="pre">MiddlewareNotUsed</span></code></a> exception is raised when a middleware is not
used in the server configuration.</p>
</dd></dl>

</div>
<div class="section" id="s-improperlyconfigured">
<span id="improperlyconfigured"></span><h3><code class="docutils literal notranslate"><span class="pre">ImproperlyConfigured</span></code><a class="headerlink" href="#improperlyconfigured" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ImproperlyConfigured">
<em class="property">exception </em><code class="descname">ImproperlyConfigured</code><a class="reference internal" href="../_modules/django/core/exceptions.html#ImproperlyConfigured"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.ImproperlyConfigured" title="永久链接至目标">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.ImproperlyConfigured" title="django.core.exceptions.ImproperlyConfigured"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ImproperlyConfigured</span></code></a> exception is raised when Django is
somehow improperly configured -- for example, if a value in <code class="docutils literal notranslate"><span class="pre">settings.py</span></code>
is incorrect or unparseable.</p>
</dd></dl>

</div>
<div class="section" id="s-fielderror">
<span id="fielderror"></span><h3><code class="docutils literal notranslate"><span class="pre">FieldError</span></code><a class="headerlink" href="#fielderror" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.FieldError">
<em class="property">exception </em><code class="descname">FieldError</code><a class="reference internal" href="../_modules/django/core/exceptions.html#FieldError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.FieldError" title="永久链接至目标">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.FieldError" title="django.core.exceptions.FieldError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">FieldError</span></code></a> exception is raised when there is a problem with a
model field. This can happen for several reasons:</p>
<ul class="simple">
<li>A field in a model clashes with a field of the same name from an
abstract base class</li>
<li>An infinite loop is caused by ordering</li>
<li>A keyword cannot be parsed from the filter parameters</li>
<li>A field cannot be determined from a keyword in the query
parameters</li>
<li>A join is not permitted on the specified field</li>
<li>A field name is invalid</li>
<li>A query contains invalid order_by arguments</li>
</ul>
</dd></dl>

</div>
<div class="section" id="s-validationerror">
<span id="validationerror"></span><h3><code class="docutils literal notranslate"><span class="pre">ValidationError</span></code><a class="headerlink" href="#validationerror" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ValidationError">
<em class="property">exception </em><code class="descname">ValidationError</code><a class="reference internal" href="../_modules/django/core/exceptions.html#ValidationError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.core.exceptions.ValidationError" title="永久链接至目标">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.ValidationError" title="django.core.exceptions.ValidationError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ValidationError</span></code></a> exception is raised when data fails form or
model field validation. For more information about validation, see
<a class="reference internal" href="forms/validation.html"><span class="doc">Form and Field Validation</span></a>,
<a class="reference internal" href="models/instances.html#validating-objects"><span class="std std-ref">Model Field Validation</span></a> and the
<a class="reference internal" href="validators.html"><span class="doc">Validator Reference</span></a>.</p>
</dd></dl>

<div class="section" id="s-non-field-errors">
<span id="non-field-errors"></span><h4><code class="docutils literal notranslate"><span class="pre">NON_FIELD_ERRORS</span></code><a class="headerlink" href="#non-field-errors" title="永久链接至标题">¶</a></h4>
<dl class="data">
<dt id="django.core.exceptions.NON_FIELD_ERRORS">
<code class="descname">NON_FIELD_ERRORS</code><a class="headerlink" href="#django.core.exceptions.NON_FIELD_ERRORS" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<p><code class="docutils literal notranslate"><span class="pre">ValidationError</span></code>s that don't belong to a particular field in a form
or model are classified as <code class="docutils literal notranslate"><span class="pre">NON_FIELD_ERRORS</span></code>. This constant is used
as a key in dictionaries that otherwise map fields to their respective
list of errors.</p>
</div>
</div>
</div>
<div class="section" id="s-url-resolver-exceptions">
<span id="url-resolver-exceptions"></span><h2>URL Resolver exceptions<a class="headerlink" href="#url-resolver-exceptions" title="永久链接至标题">¶</a></h2>
<p>URL Resolver exceptions are defined in <code class="docutils literal notranslate"><span class="pre">django.urls</span></code>.</p>
<div class="section" id="s-resolver404">
<span id="resolver404"></span><h3><code class="docutils literal notranslate"><span class="pre">Resolver404</span></code><a class="headerlink" href="#resolver404" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.urls.Resolver404">
<em class="property">exception </em><code class="descname">Resolver404</code><a class="reference internal" href="../_modules/django/urls/exceptions.html#Resolver404"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.urls.Resolver404" title="永久链接至目标">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.urls.Resolver404" title="django.urls.Resolver404"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Resolver404</span></code></a> exception is raised by
<a class="reference internal" href="urlresolvers.html#django.urls.resolve" title="django.urls.resolve"><code class="xref py py-func docutils literal notranslate"><span class="pre">resolve()</span></code></a> if the path passed to <code class="docutils literal notranslate"><span class="pre">resolve()</span></code> doesn't
map to a view. It's a subclass of <a class="reference internal" href="../topics/http/views.html#django.http.Http404" title="django.http.Http404"><code class="xref py py-class docutils literal notranslate"><span class="pre">django.http.Http404</span></code></a>.</p>
</dd></dl>

</div>
<div class="section" id="s-noreversematch">
<span id="noreversematch"></span><h3><code class="docutils literal notranslate"><span class="pre">NoReverseMatch</span></code><a class="headerlink" href="#noreversematch" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.urls.NoReverseMatch">
<em class="property">exception </em><code class="descname">NoReverseMatch</code><a class="reference internal" href="../_modules/django/urls/exceptions.html#NoReverseMatch"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.urls.NoReverseMatch" title="永久链接至目标">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.urls.NoReverseMatch" title="django.urls.NoReverseMatch"><code class="xref py py-exc docutils literal notranslate"><span class="pre">NoReverseMatch</span></code></a> exception is raised by <a class="reference internal" href="urlresolvers.html#module-django.urls" title="django.urls"><code class="xref py py-mod docutils literal notranslate"><span class="pre">django.urls</span></code></a> when a
matching URL in your URLconf cannot be identified based on the parameters
supplied.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-database-exceptions">
<span id="database-exceptions"></span><h2>Database Exceptions<a class="headerlink" href="#database-exceptions" title="永久链接至标题">¶</a></h2>
<p>Database exceptions may be imported from <code class="docutils literal notranslate"><span class="pre">django.db</span></code>.</p>
<p>Django wraps the standard database exceptions so that your Django code has a
guaranteed common implementation of these classes.</p>
<dl class="exception">
<dt id="django.db.Error">
<em class="property">exception </em><code class="descname">Error</code><a class="reference internal" href="../_modules/django/db/utils.html#Error"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.db.Error" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.InterfaceError">
<em class="property">exception </em><code class="descname">InterfaceError</code><a class="reference internal" href="../_modules/django/db/utils.html#InterfaceError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.db.InterfaceError" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.DatabaseError">
<em class="property">exception </em><code class="descname">DatabaseError</code><a class="reference internal" href="../_modules/django/db/utils.html#DatabaseError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.db.DatabaseError" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.DataError">
<em class="property">exception </em><code class="descname">DataError</code><a class="reference internal" href="../_modules/django/db/utils.html#DataError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.db.DataError" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.OperationalError">
<em class="property">exception </em><code class="descname">OperationalError</code><a class="reference internal" href="../_modules/django/db/utils.html#OperationalError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.db.OperationalError" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.IntegrityError">
<em class="property">exception </em><code class="descname">IntegrityError</code><a class="reference internal" href="../_modules/django/db/utils.html#IntegrityError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.db.IntegrityError" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.InternalError">
<em class="property">exception </em><code class="descname">InternalError</code><a class="reference internal" href="../_modules/django/db/utils.html#InternalError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.db.InternalError" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.ProgrammingError">
<em class="property">exception </em><code class="descname">ProgrammingError</code><a class="reference internal" href="../_modules/django/db/utils.html#ProgrammingError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.db.ProgrammingError" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.NotSupportedError">
<em class="property">exception </em><code class="descname">NotSupportedError</code><a class="reference internal" href="../_modules/django/db/utils.html#NotSupportedError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.db.NotSupportedError" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<p>The Django wrappers for database exceptions behave exactly the same as
the underlying database exceptions. See <span class="target" id="index-0"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0249"><strong>PEP 249</strong></a>, the Python Database API
Specification v2.0, for further information.</p>
<p>As per <span class="target" id="index-1"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-3134"><strong>PEP 3134</strong></a>, a <code class="docutils literal notranslate"><span class="pre">__cause__</span></code> attribute is set with the original
(underlying) database exception, allowing access to any additional
information provided.</p>
<dl class="exception">
<dt id="django.db.models.ProtectedError">
<em class="property">exception </em><code class="descclassname">models.</code><code class="descname">ProtectedError</code><a class="headerlink" href="#django.db.models.ProtectedError" title="永久链接至目标">¶</a></dt>
<dd></dd></dl>

<p>Raised to prevent deletion of referenced objects when using
<a class="reference internal" href="models/fields.html#django.db.models.PROTECT" title="django.db.models.PROTECT"><code class="xref py py-attr docutils literal notranslate"><span class="pre">django.db.models.PROTECT</span></code></a>. <a class="reference internal" href="#django.db.models.ProtectedError" title="django.db.models.ProtectedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">models.ProtectedError</span></code></a> is a subclass
of <a class="reference internal" href="#django.db.IntegrityError" title="django.db.IntegrityError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IntegrityError</span></code></a>.</p>
</div>
<div class="section" id="s-http-exceptions">
<span id="http-exceptions"></span><h2>Http Exceptions<a class="headerlink" href="#http-exceptions" title="永久链接至标题">¶</a></h2>
<p>Http exceptions may be imported from <code class="docutils literal notranslate"><span class="pre">django.http</span></code>.</p>
<div class="section" id="s-unreadableposterror">
<span id="unreadableposterror"></span><h3><code class="docutils literal notranslate"><span class="pre">UnreadablePostError</span></code><a class="headerlink" href="#unreadableposterror" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.http.UnreadablePostError">
<em class="property">exception </em><code class="descname">UnreadablePostError</code><a class="reference internal" href="../_modules/django/http/request.html#UnreadablePostError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.http.UnreadablePostError" title="永久链接至目标">¶</a></dt>
<dd><p><a class="reference internal" href="#django.http.UnreadablePostError" title="django.http.UnreadablePostError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnreadablePostError</span></code></a> is raised when a user cancels an upload.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-transaction-exceptions">
<span id="transaction-exceptions"></span><h2>Transaction Exceptions<a class="headerlink" href="#transaction-exceptions" title="永久链接至标题">¶</a></h2>
<p>Transaction exceptions are defined in <code class="docutils literal notranslate"><span class="pre">django.db.transaction</span></code>.</p>
<div class="section" id="s-transactionmanagementerror">
<span id="transactionmanagementerror"></span><h3><code class="docutils literal notranslate"><span class="pre">TransactionManagementError</span></code><a class="headerlink" href="#transactionmanagementerror" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.db.transaction.TransactionManagementError">
<em class="property">exception </em><code class="descname">TransactionManagementError</code><a class="reference internal" href="../_modules/django/db/transaction.html#TransactionManagementError"><span class="viewcode-link">[源代码]</span></a><a class="headerlink" href="#django.db.transaction.TransactionManagementError" title="永久链接至目标">¶</a></dt>
<dd><p><a class="reference internal" href="#django.db.transaction.TransactionManagementError" title="django.db.transaction.TransactionManagementError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TransactionManagementError</span></code></a> is raised for any and all problems
related to database transactions.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-testing-framework-exceptions">
<span id="testing-framework-exceptions"></span><h2>Testing Framework Exceptions<a class="headerlink" href="#testing-framework-exceptions" title="永久链接至标题">¶</a></h2>
<p>Exceptions provided by the <code class="docutils literal notranslate"><span class="pre">django.test</span></code> package.</p>
<div class="section" id="s-redirectcycleerror">
<span id="redirectcycleerror"></span><h3><code class="docutils literal notranslate"><span class="pre">RedirectCycleError</span></code><a class="headerlink" href="#redirectcycleerror" title="永久链接至标题">¶</a></h3>
<dl class="exception">
<dt id="django.test.client.RedirectCycleError">
<em class="property">exception </em><code class="descclassname">client.</code><code class="descname">RedirectCycleError</code><a class="headerlink" href="#django.test.client.RedirectCycleError" title="永久链接至目标">¶</a></dt>
<dd><p><a class="reference internal" href="#django.test.client.RedirectCycleError" title="django.test.client.RedirectCycleError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RedirectCycleError</span></code></a> is raised when the test client detects a
loop or an overly long chain of redirects.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-python-exceptions">
<span id="python-exceptions"></span><h2>Python Exceptions<a class="headerlink" href="#python-exceptions" title="永久链接至标题">¶</a></h2>
<p>Django raises built-in Python exceptions when appropriate as well. See the
Python documentation for further information on the <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#bltin-exceptions" title="(在 Python v3.7)"><span>Built-in Exceptions</span></a>.</p>
</div>
</div>


          </div>
        </div>
      </div>
      
        
          <div class="yui-b" id="sidebar">
            
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="../contents.html">Table of Contents</a></h3>
  <ul>
<li><a class="reference internal" href="#">Django Exceptions</a><ul>
<li><a class="reference internal" href="#module-django.core.exceptions">Django Core Exceptions</a><ul>
<li><a class="reference internal" href="#appregistrynotready"><code class="docutils literal notranslate"><span class="pre">AppRegistryNotReady</span></code></a></li>
<li><a class="reference internal" href="#objectdoesnotexist"><code class="docutils literal notranslate"><span class="pre">ObjectDoesNotExist</span></code></a></li>
<li><a class="reference internal" href="#emptyresultset"><code class="docutils literal notranslate"><span class="pre">EmptyResultSet</span></code></a></li>
<li><a class="reference internal" href="#fielddoesnotexist"><code class="docutils literal notranslate"><span class="pre">FieldDoesNotExist</span></code></a></li>
<li><a class="reference internal" href="#multipleobjectsreturned"><code class="docutils literal notranslate"><span class="pre">MultipleObjectsReturned</span></code></a></li>
<li><a class="reference internal" href="#suspiciousoperation"><code class="docutils literal notranslate"><span class="pre">SuspiciousOperation</span></code></a></li>
<li><a class="reference internal" href="#permissiondenied"><code class="docutils literal notranslate"><span class="pre">PermissionDenied</span></code></a></li>
<li><a class="reference internal" href="#viewdoesnotexist"><code class="docutils literal notranslate"><span class="pre">ViewDoesNotExist</span></code></a></li>
<li><a class="reference internal" href="#middlewarenotused"><code class="docutils literal notranslate"><span class="pre">MiddlewareNotUsed</span></code></a></li>
<li><a class="reference internal" href="#improperlyconfigured"><code class="docutils literal notranslate"><span class="pre">ImproperlyConfigured</span></code></a></li>
<li><a class="reference internal" href="#fielderror"><code class="docutils literal notranslate"><span class="pre">FieldError</span></code></a></li>
<li><a class="reference internal" href="#validationerror"><code class="docutils literal notranslate"><span class="pre">ValidationError</span></code></a><ul>
<li><a class="reference internal" href="#non-field-errors"><code class="docutils literal notranslate"><span class="pre">NON_FIELD_ERRORS</span></code></a></li>
</ul>
</li>
</ul>
</li>
<li><a class="reference internal" href="#url-resolver-exceptions">URL Resolver exceptions</a><ul>
<li><a class="reference internal" href="#resolver404"><code class="docutils literal notranslate"><span class="pre">Resolver404</span></code></a></li>
<li><a class="reference internal" href="#noreversematch"><code class="docutils literal notranslate"><span class="pre">NoReverseMatch</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#database-exceptions">Database Exceptions</a></li>
<li><a class="reference internal" href="#http-exceptions">Http Exceptions</a><ul>
<li><a class="reference internal" href="#unreadableposterror"><code class="docutils literal notranslate"><span class="pre">UnreadablePostError</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#transaction-exceptions">Transaction Exceptions</a><ul>
<li><a class="reference internal" href="#transactionmanagementerror"><code class="docutils literal notranslate"><span class="pre">TransactionManagementError</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#testing-framework-exceptions">Testing Framework Exceptions</a><ul>
<li><a class="reference internal" href="#redirectcycleerror"><code class="docutils literal notranslate"><span class="pre">RedirectCycleError</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#python-exceptions">Python Exceptions</a></li>
</ul>
</li>
</ul>

  <h4>上一个主题</h4>
  <p class="topless"><a href="django-admin.html"
                        title="上一章"><code class="docutils literal notranslate"><span class="pre">django-admin</span></code> and <code class="docutils literal notranslate"><span class="pre">manage.py</span></code></a></p>
  <h4>下一个主题</h4>
  <p class="topless"><a href="files/index.html"
                        title="下一章">File handling</a></p>
  <div role="note" aria-label="source link">
    <h3>本页</h3>
    <ul class="this-page-menu">
      <li><a href="../_sources/ref/exceptions.txt"
            rel="nofollow">显示源代码</a></li>
    </ul>
   </div>
<div id="searchbox" style="display: none" role="search">
  <h3>快速搜索</h3>
    <div class="searchformwrapper">
    <form class="search" action="../search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="转向" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    </div>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
              <h3>Last update:</h3>
              <p class="topless">3月 30, 2019</p>
          </div>
        
      
    </div>

    <div id="ft">
      <div class="nav">
    &laquo; <a href="django-admin.html" title="&lt;code class=&#34;docutils literal notranslate&#34;&gt;&lt;span class=&#34;pre&#34;&gt;django-admin&lt;/span&gt;&lt;/code&gt; and &lt;code class=&#34;docutils literal notranslate&#34;&gt;&lt;span class=&#34;pre&#34;&gt;manage.py&lt;/span&gt;&lt;/code&gt;">previous</a>
     |
    <a href="index.html" title="API Reference" accesskey="U">up</a>
   |
    <a href="files/index.html" title="File handling">next</a> &raquo;</div>
    </div>
  </div>

      <div class="clearer"></div>
    </div>
  </body>
</html>